services:
#  Dual DB Application Service
  dual-db-app:
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      mongo-db:
        condition: service_healthy
      sql-db:
        condition: service_healthy
    environment:
      - MONGO_URL=mongodb://mongo-db:27017/logs
      - MYSQL_HOST=sql-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=user_db
    networks:
      - dual-db-network
    restart: on-failure

#  MongoDB Service
  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dual-db-network
    volumes:
      - mongo-data:/data/db
#  MySQL Service
  sql-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=user_db
    ports:
      - "3306:3306"
    networks:
      - dual-db-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s


#  Network Definition
networks:
  dual-db-network:
    driver: bridge
# Volumes for MongoDB and MySQL
volumes:
  mongo-data:
  mysql-data: